### ISSUE TITLE
Подготовить подложки для перехода между сценами(option)

### ISSUE THREAD

**Issue by MyDanielM** [MyDanielM/history-of-IDE#4]
Пример: (скачай, посмотри пример, можно анимашку, можно видос)
https://drive.google.com/open?id=0B5zXbfKdESILUTFDSDNveUpmRlU

**Comment by Yashka71** [comment]
https://drive.google.com/drive/folders/1mdQH6CDhYnSyh_i_sQ-JhiB8z4Gzn9xy?usp=sharing
