### ISSUE TITLE
Подготовить элементы общения

### ISSUE THREAD

**Issue by MyDanielM** [MyDanielM/history-of-IDE#6]
Подготовить элементы "подпишись", "поставь лайк", "включи оповещения". Пример: 
![image](https://user-images.githubusercontent.com/58218182/79601019-cf7fff80-80f0-11ea-82c0-d28a929efb68.png)

**Comment by Mary813** [comment]
https://drive.google.com/open?id=1JXvv5__I9uhhUoXCXZYnFvZi02Jjzbe6
